### ISSUE TITLE
Bundler adds BUNDLED WITH 'version' on the bottom of Gemfile.lock file

### ISSUE THREAD

**Issue by ag4ta** [agoraspeakers/meetings-portal#15]
CircleCI fails:
```
#!/bin/bash -eo pipefail
bundle install --jobs=4 --retry=3 --path vendor/bundle
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in '<main>'
	1: from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in 'activate_bin_path'
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in 'find_spec_for_exe': Could not find 'bundler' (2.1.0.pre.1) required by your /home/circleci/repo/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run 'bundle update --bundler'.
To install the missing version, run 'gem install bundler:2.1.0.pre.1'
Exited with code 1
```

**Comment by mpapis** [comment]
solved in #16
